version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - src/main/resources/.env
    depends_on:
      - mongo
    restart: always
  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: bot
      MONGO_INITDB_ROOT_PASSWORD: bot
    volumes:
      - mongo-data:/data/db
    image: mongo
    restart: always

volumes:
  mongo-data: { }